---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: autoscale-fixed-amount
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "100"
        autoscaling.knative.dev/initial-scale: "20"
        autoscaling.knative.dev/min-scale: "20"
        autoscaling.knative.dev/max-scale: "20"
        autoscaling.knative.dev/target-burst-capacity: "-1"
    spec:
      containers:
        - image: gcr.io/knative-samples/autoscale-go:0.1

