apiVersion: v1
kind: Namespace
metadata:
  name: visualization
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: visualization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy: {}
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - image: prom/prometheus:v2.42.0
          name: prometheus
          command:
            - /bin/prometheus
            - --web.enable-remote-write-receiver
            - --enable-feature=native-histograms
            - --config.file=/etc/prometheus/prometheus.yml
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: visualization
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus