---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: autoscale-delay-15s-COUNT
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/initial-scale: "0"
    spec:
      containers:
        - image: gcr.io/knative-samples/autoscale-go:0.1
      initContainers:
        - image: busybox
          command: ['sh', '-c', 'sleep 15']
